In [1]:
import pandas as pd
import warnings
warnings.filterwarnings(action= "ignore")

In [2]:
import os  
os.getcwd() # 현재 경로 확인

'/Users/yoonsung/YS_project/Final_Project/ResaleShoes'

In [3]:
path =  'data/transactions_nike_air_force/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')] ## 파일명 끝이 .csv인 경우

In [4]:
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i)
    df = pd.concat([df,data], ignore_index  = True)

In [5]:
df

,Unnamed: 0,size,price,date,product,release_date,color,release_price
0,0,240,"180,000원",20/10/25,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
1,1,235,"120,000원",21/03/03,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
2,2,270,"198,000원",21/08/08,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
3,0,235(4.5Y),"179,000원",21/05/22,(GS) Nike Air Force 1 LV8 Double Swoosh,21/01/27,WHITE/LIGHTARMORYBLUE/ARCTICPUNCH,"$90(약108,300원)"
4,1,245(6.5Y),"189,000원",21/05/23,(GS) Nike Air Force 1 LV8 Double Swoosh,21/01/27,WHITE/LIGHTARMORYBLUE/ARCTICPUNCH,"$90(약108,300원)"
...,...,...,...,...,...,...,...,...
88472,413,270,"241,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88473,414,220,"295,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88474,415,220,"299,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88475,416,235,"218,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88476,417,235,"219,000원",22/01/08,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"

In [6]:
df = df.drop("Unnamed: 0" , axis = 1)

In [7]:
df

,size,price,date,product,release_date,color,release_price
0,240,"180,000원",20/10/25,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
1,235,"120,000원",21/03/03,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
2,270,"198,000원",21/08/08,(W) Nike Air Force 1 LXX Game Royal University...,20/10/17,WHITE/GAMEROYAL-UNIVERSITYRED,"$110(약132,300원)"
3,235(4.5Y),"179,000원",21/05/22,(GS) Nike Air Force 1 LV8 Double Swoosh,21/01/27,WHITE/LIGHTARMORYBLUE/ARCTICPUNCH,"$90(약108,300원)"
4,245(6.5Y),"189,000원",21/05/23,(GS) Nike Air Force 1 LV8 Double Swoosh,21/01/27,WHITE/LIGHTARMORYBLUE/ARCTICPUNCH,"$90(약108,300원)"
...,...,...,...,...,...,...,...
88472,270,"241,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88473,220,"295,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88474,220,"299,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88475,235,"218,000원",22/01/07,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"
88476,235,"219,000원",22/01/08,(W) Nike Air Force 1 Fontanka Pearl White,21/10/18,PEARLWHITE/PEARLWHITE/UNIVERSITYRED/PEARLWHITE,"149,000원"

In [8]:
df.to_csv('data/nike_air_force(raw).csv', index=False)