In [2]:
import pandas as pd
import warnings
warnings.filterwarnings(action= "ignore")

In [3]:
import os  
os.getcwd() # 현재 경로 확인

'/Users/yoonsung/YS_project/Final_Project/ResaleShoes'

In [4]:
path =  'data/nike_dunk_low/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')] ## 파일명 끝이 .csv인 경우

In [5]:
df = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i)
    df = pd.concat([df,data], ignore_index  = True)

In [6]:
df

,Unnamed: 0,size,price,date,product,release_date,color,release_price
0,0,245,"125,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
1,1,240,"123,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
2,2,245,"129,000원",21/10/01,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
3,3,275,"129,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
4,4,240,"132,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
...,...,...,...,...,...,...,...,...
173727,127,260,"231,000원",21/07/15,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173728,128,260,"250,000원",21/08/17,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173729,129,245,"280,000원",21/09/26,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173730,130,280,"250,000원",21/10/05,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173731,131,270,"390,000원",21/10/08,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"

In [7]:
df = df.drop("Unnamed: 0" , axis = 1)

In [8]:
df

,size,price,date,product,release_date,color,release_price
0,245,"125,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
1,240,"123,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
2,245,"129,000원",21/10/01,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
3,275,"129,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
4,240,"132,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
...,...,...,...,...,...,...,...
173727,260,"231,000원",21/07/15,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173728,260,"250,000원",21/08/17,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173729,245,"280,000원",21/09/26,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173730,280,"250,000원",21/10/05,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"
173731,270,"390,000원",21/10/08,Nike SB Dunk Low Pro Midnight Navy,20/11/17,MIDNIGHTNAVY/BLACK/MIDNIGHTNAVY,"119,000원"

In [9]:
path =  'data/transactions_dunk_high/'
file_list = os.listdir(path)
file_list_py = [file for file in file_list if file.endswith('.csv')] ## 파일명 끝이 .csv인 경우

In [10]:
df2 = pd.DataFrame()
for i in file_list_py:
    data = pd.read_csv(path + i)
    df2 = pd.concat([df2,data], ignore_index  = True)

In [12]:
df2 = df2.drop("Unnamed: 0" , axis = 1)

In [13]:
df2

,size,price,date,product,release_date,color,release_price
0,280,"399,000원",21/12/14,Nike Dunk High Retro University Red,21/11/19,WHITE/UNIVERSITYRED,"$110(약132,300원)"
1,270,"399,000원",21/12/26,Nike Dunk High Retro University Red,21/11/19,WHITE/UNIVERSITYRED,"$110(약132,300원)"
2,260,"150,000원",21/08/15,(W) Nike Dunk High Up Varsity Maize,21/08/15,VARSITYMAIZE/MIDNIGHTNAVY-UNIVERSITYRED,"139,000원"
3,240,"134,000원",21/08/18,(W) Nike Dunk High Up Varsity Maize,21/08/15,VARSITYMAIZE/MIDNIGHTNAVY-UNIVERSITYRED,"139,000원"
4,255,"139,000원",21/08/27,(W) Nike Dunk High Up Varsity Maize,21/08/15,VARSITYMAIZE/MIDNIGHTNAVY-UNIVERSITYRED,"139,000원"
...,...,...,...,...,...,...,...
50205,240,"238,000원",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
50206,235,"223,000원",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
50207,255,"260,000원빠른배송",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
50208,245,"248,000원",22/01/07,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
50209,245,"268,000원빠른배송",22/01/07,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"

In [16]:
data = pd.concat([df, df2]).reset_index(drop=True)

In [17]:
data

,size,price,date,product,release_date,color,release_price
0,245,"125,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
1,240,"123,000원",21/09/30,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
2,245,"129,000원",21/10/01,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
3,275,"129,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
4,240,"132,000원",21/10/04,(W) Nike Dunk Low SE Primal Black,21/11/07,BLACK/MULTI-COLOR/BLACK,"129,000원"
...,...,...,...,...,...,...,...
223937,240,"238,000원",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
223938,235,"223,000원",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
223939,255,"260,000원빠른배송",22/01/06,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
223940,245,"248,000원",22/01/07,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"
223941,245,"268,000원빠른배송",22/01/07,(W) Nike Dunk High Black and White,21/05/01,WHITE/BLACK-UNIVERSITYRED,"129,000원"

In [18]:
data.to_csv('data/nike_dunk(raw).csv', index=False)